name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  sql:
    runs-on: ubuntu-latest
    steps:
      - name: Run sql script
        run: |
          mysql --version
          sleep 20
          mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam < rfam.sql
