name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  sql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam < rfam.sql
          
